name: AfterCore
main: com.afterlands.core.AfterCorePlugin
version: 1.5.3
build-date: '${maven.build.timestamp}'
author: AfterLands
description: AfterLands - Core Library Plugin
softdepend: [ProtocolLib, PlaceholderAPI, DecentHolograms]

commands:
  acore:
    description: AfterCore diagnostics and admin commands
    usage: /acore <status|db|threads|system|metrics|all>
    permission: aftercore.admin
    permission-message: You don't have permission to use this command

permissions:
  aftercore.admin:
    description: Access to AfterCore admin commands
    default: op

